require('core.lazy')
require('core.options')
require('core.mappings')
require('core.autocommands')
require('core.commands')
require('plugins.neo-tree')
require('plugins.statuscol')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.spectre')
require('lsp.coc')
require('themes.current-theme')

