require('core.lazy')
require('core.options')
require('core.mappings')
require('core.autocommands')
require('core.commands')
require('lsp.lspconfig')
require('plugins.neo-tree')
require('plugins.nvim-cmp')
require('plugins.mason-lspconfig')
require('plugins.statuscol')
require('plugins.lualine')

